### ISSUE TITLE
Connector-oplysninger Error: DS_USER:Error

### ISSUE THREAD

**Issue by andersbirkmose** [Gladior-B-V/facebook-insights-connector#1]
Hi
I get the following error when I want to connect my data source. 
<img width="1049" alt="Skærmbillede 2021-02-10 kl  08 39 28" src="https://user-images.githubusercontent.com/4482689/107479542-8ca97f80-6b7b-11eb-89c5-97d604b747e0.png">

**Comment by daannijkamp** [comment]
@andersbirkmose Thanks for reporting! I'm going to investigate what's causing this.

**Comment by daannijkamp** [comment]
@andersbirkmose For some reason I am getting reports that something went wrong during the authentication process.
Could you do this again? 
To do this, you must first revoke access in Data Studio and Facebook.
(You do not have to request the Gladior account token / api key again)

Google Data Studio
![Screenshot from 2021-02-10 11-08-10](https://user-images.githubusercontent.com/1774060/107495885-f1bba000-6b90-11eb-9d3c-c9acd503bfda.png)

Facebook Business Tools
(https://www.facebook.com/settings?tab=business_tools&ref=settings)
![Screenshot from 2021-02-10 11-15-11](https://user-images.githubusercontent.com/1774060/107496181-47904800-6b91-11eb-9dd7-c756ed71bc19.png)

**Comment by buffalodebile** [comment]
Hi,

I also have a problem with The Gladior FB data connector for data studio.

When I connect, link my FB page and use the default template, data do not display. Is this Connector up to date?

Another question: Do you have another Free template for Instagram Insight?

Thanks!

**Comment by daannijkamp** [comment]
Hi @BuffaloDebile,

I'm going to look into it. 

You can help me a lot by sending the facebook fan page id or name. You may also email data-dashboards@gladior.com
(The connector is up to date and is used and monitored on a daily basis.)

Unfortunately, we don't have an Instagram Insight connector / template at this time. Maybe in the future ;-)!

-Daan

**Comment by buffalodebile** [comment]
Alright, I will do that.

Thanks a lot Dann for your work on the only free social media data connectors available out there :) Keep it up.

**Comment by Cesario17** [comment]
Hi:
I'm getting an error message from the Facebook Insights connector:
 _Community Connector Error
There was an error caused by the community connector. Please report the issue to the provider of this community connector if this issue persists.

Connector details
Error: DS_USER:Error_

I revoked access from my Google account and from Facebook and granted it again, but it still doesn't work. My FB page ID is 271391433538309. Hope you can help me.

Thank you for your work!

**Comment by DanielM1977** [comment]
Also having the same issue Error: DS_USER:Error_
Revoked access in facebook and data studio and google but cant pass problem.

**Comment by daannijkamp** [comment]
Hi @Cesario17 & @DanielM1977,

Sorry for the delay. Can you maybe try again? You can help me by sending the time of try + FB page ID. You may also email it to data-dashboards@gladior.com.

Unfortunately, it is not easy to debug this within Google Data Studio. Especially because that error does not occur with our dashboards.

**Comment by Cesario17** [comment]
Thanks for the reply.
This is my FB page ID: 271391433538309. I just tried 5 mins ago, and I'm still getting the same error message. 
![image](https://user-images.githubusercontent.com/84814326/123526402-458cd880-d69d-11eb-94db-5486621f0734.png)

I'm going to email it to data-dashboards@gladior.com.
Thanks for your work...
