### ISSUE TITLE
Total page fans and age demografics missing

### ISSUE THREAD

**Issue by ESGITR** [Gladior-B-V/facebook-insights-connector#18]
The total page fans aren't displaying correctly and the age demographics of the fans aren't available.

**Comment by rkooiker** [comment]
Hi @ESGITR, Facebook has recently deprecated the page fans gender and age metrics, so this field is no longer available. The amount of total page fans is working for us. Make sure you are looking at the right place in facebook, since page fans refers to the amount of likes on your page, not the amount of followers.
