### ISSUE TITLE
No Credentials found

### ISSUE THREAD

**Issue by ESGITR** [Gladior-B-V/facebook-insights-connector#9]
I can't connect. All my page credentials are active in data hub.
![image](https://user-images.githubusercontent.com/99658324/215540116-19350535-4eba-42a2-ae43-e5d7a1b443ec.png)

**Comment by zoedufrenne** [comment]
@ESGITR Did you create a new data source in Looker Studio?

If you use the pencil tool to adjust the 'old' source it won't work because it will redirect to your old workspace.
You have to connect the source to all the widgets in your dashboard. You won't have to select all the metrics & dimensions because this will connect automatically.

**Comment by ESGITR** [comment]
Yes I did. I tried everything... I even revoked all creditials.
I also get the same error when I create a new dashboard from the Gladiator hub using your template.

**Comment by zoedufrenne** [comment]
@ESGITR, when I check the screenshot you've send I see that there are no credentials found (in Facebook Insights). When you click the link (that I see in your screenshot). What do you see? Can you add credentials to the datahubapp.gladior.com ?

**Comment by ESGITR** [comment]
Yes I can.
![image](https://user-images.githubusercontent.com/99658324/215782875-1278445b-acfb-41dd-9c2a-f104465bc5fb.png)

**Comment by zoedufrenne** [comment]
Okay and when you click on a source and connect it to our Looker Studio template, you'll get the error as mentioned above right? Could you maybe send your user id? datahubapp.gladior.com -> Edit Profile -> gray ID at the bottom of the page
